/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'heroBannerEnabled' : boolean,
  'heroBannerHeadline' : string,
}
export interface CustomerProfile {
  'name' : string,
  'updatedAt' : bigint,
  'address' : string,
  'phone' : string,
}
export interface DiscountSettings {
  'flatMinOrder' : bigint,
  'percentageMinOrder' : bigint,
  'freeItemName' : string,
  'percentageOff' : bigint,
  'freeItemMinOrder' : bigint,
  'flatOff' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'freeItem' : string,
  'paymentMethod' : string,
  'customerPhone' : string,
  'discountAmount' : bigint,
  'createdAt' : bigint,
  'discountType' : string,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'itemTotal' : bigint,
  'productId' : bigint,
  'productName' : string,
  'quantityLabel' : string,
  'unitPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'unitType' : string,
  'productCategory' : string,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageId' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addCustomSlide' : ActorMethod<[string], bigint>,
  'addProduct' : ActorMethod<
    [string, bigint, bigint, string, string, string, string],
    bigint
  >,
  'deleteCustomSlide' : ActorMethod<[bigint], boolean>,
  'deleteOrder' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllProfiles' : ActorMethod<[], Array<CustomerProfile>>,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getCustomSlides' : ActorMethod<[], Array<[bigint, string]>>,
  'getDeliveryTiming' : ActorMethod<[], string>,
  'getDiscountSettings' : ActorMethod<[], DiscountSettings>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProfile' : ActorMethod<[string], [] | [CustomerProfile]>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<OrderItem>,
      bigint,
      bigint,
      string,
      string,
      bigint,
    ],
    bigint
  >,
  'saveProfile' : ActorMethod<[string, string, string], boolean>,
  'setAppSettings' : ActorMethod<[boolean, string], boolean>,
  'setDeliveryTiming' : ActorMethod<[string], boolean>,
  'setDiscountSettings' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, bigint],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, bigint, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];