/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'heroBannerEnabled' : IDL.Bool,
  'heroBannerHeadline' : IDL.Text,
});
export const DiscountSettings = IDL.Record({
  'flatMinOrder' : IDL.Nat,
  'percentageMinOrder' : IDL.Nat,
  'freeItemName' : IDL.Text,
  'percentageOff' : IDL.Nat,
  'freeItemMinOrder' : IDL.Nat,
  'flatOff' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'itemTotal' : IDL.Nat,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantityLabel' : IDL.Text,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'freeItem' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customerPhone' : IDL.Text,
  'discountAmount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'discountType' : IDL.Text,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'unitType' : IDL.Text,
  'productCategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageId' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomSlide' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCustomSlide' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(CustomerProfile)], ['query']),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'getCustomSlides' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getDeliveryTiming' : IDL.Func([], [IDL.Text], ['query']),
  'getDiscountSettings' : IDL.Func([], [DiscountSettings], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(CustomerProfile)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'setAppSettings' : IDL.Func([IDL.Bool, IDL.Text], [IDL.Bool], []),
  'setDeliveryTiming' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setDiscountSettings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerProfile = IDL.Record({
    'name' : IDL.Text,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'heroBannerEnabled' : IDL.Bool,
    'heroBannerHeadline' : IDL.Text,
  });
  const DiscountSettings = IDL.Record({
    'flatMinOrder' : IDL.Nat,
    'percentageMinOrder' : IDL.Nat,
    'freeItemName' : IDL.Text,
    'percentageOff' : IDL.Nat,
    'freeItemMinOrder' : IDL.Nat,
    'flatOff' : IDL.Nat,
  });
  const OrderItem = IDL.Record({
    'itemTotal' : IDL.Nat,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantityLabel' : IDL.Text,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'freeItem' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customerPhone' : IDL.Text,
    'discountAmount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'discountType' : IDL.Text,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'unitType' : IDL.Text,
    'productCategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageId' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomSlide' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCustomSlide' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(CustomerProfile)], ['query']),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'getCustomSlides' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getDeliveryTiming' : IDL.Func([], [IDL.Text], ['query']),
    'getDiscountSettings' : IDL.Func([], [DiscountSettings], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(CustomerProfile)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'setAppSettings' : IDL.Func([IDL.Bool, IDL.Text], [IDL.Bool], []),
    'setDeliveryTiming' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setDiscountSettings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };